name: Deploy to AWS

on:
  push:
    tags:
      - 'v20*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy to S3
        run: |
          aws s3 cp index.html s3://www.desmondgc.com/index.html
          aws s3 cp favicon.ico s3://www.desmondgc.com/favicon.ico
